wip

diff --git a/.github/workflows/create.yaml b/.github/workflows/create.yaml
--- a/.github/workflows/create.yaml
+++ b/.github/workflows/create.yaml
@@ -39,4 +39,4 @@ jobs:
       - name: Show .npmrc token line (masked)
         run: |
           echo "Token line in .npmrc:"
-          grep "//hub.xeditor.com/repository/xeditor/:_authToken" ~/.npmrc || echo "Token not found"
+          cat ~/.npmrc || echo "Token not found"
